version: "3.7"

services:
  app:
    build: ./docker
    image: temo/laravel
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
  db:
    image: mysql/mysql-server:8.0
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql-config.cnf:/etc/mysql/conf.d/config.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: selftest
      MYSQL_USER: selftest
      MYSQL_PASSWORD: password
#    networks:
#      - mysql-phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    links:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
      UPLOAD_LIMIT: 102400M
#    networks:
#      - mysql-phpmyadmin
#networks:
#  mysql-phpmyadmin:

volumes:
  mysql-data: